version: '3.4'

x-app: &app
  image: beabee/beabee:stable
  env_file:
    - .env
  logging:
    driver: syslog
    options:
      tag: docker/{{.Name}}

services:
  app: *app

  api_app:
    <<: *app
    command: 'node built/api/app'

  webhook_app:
    <<: *app
    command: 'node built/webhooks/app'

  img_upload_app:
    image: hascheksolutions/pictshare:72394f17
    environment:
      CONTENTCONTROLLERS: IMAGE,TEXT
    init: true
    volumes:
      - ./data/uploads:/var/www/data

  cron:
    <<: *app
    user: root
    command: 'crond -f -d 7'
    init: true

  router:
    image: beabee/router:stable

  run:
    <<: *app
    profiles:
      - tools
    logging:
      driver: none

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        APP_BASE_URL: ${BEABEE_AUDIENCE}
        APP_LOCALE: ${BEABEE_LOCALE}
        STRIPE_PUBLIC_KEY: ${BEABEE_STRIPE_PUBLICKEY}
        STRIPE_COUNTRY: ${BEABEE_STRIPE_COUNTRY}

  app_router:
    image: beabee/app-router:latest
    environment:
      LEGACY_APP_URL: http://router
      LEGACY_APP_COOKIE_DOMAIN: ${BEABEE_COOKIE_DOMAIN}
      FRONTEND_APP_URL: http://frontend
    ports:
      - ${MAIN_PORT}:80
