version: '3.4'

x-app: &app
  image: beabee/beabee:stable
  restart: always
  env_file:
    - .env
  logging:
    driver: syslog
    options:
      tag: docker/{{.Name}}

services:
  app: *app

  api_app:
    <<: *app
    command: 'node built/api/app'

  webhook_app:
    <<: *app
    command: 'node built/webhooks/app'

  img_upload_app:
    image: hascheksolutions/pictshare:72394f17
    restart: always
    environment:
      CONTENTCONTROLLERS: IMAGE,TEXT
    init: true
    volumes:
      - ./data/uploads:/var/www/data

  cron:
    <<: *app
    user: root
    command: 'crond -f -d 7'
    init: true

  router:
    image: beabee/router:stable
    restart: always

  run:
    <<: *app
    profiles:
      - tools
    logging:
      driver: none

  frontend:
    image: beabee/frontend:stable
    restart: always
    environment:
      APP_BASE_URL: ${BEABEE_AUDIENCE}
      API_BASE_URL: /api/1.0

  app_router:
    image: beabee/app-router:latest
    restart: always
    environment:
      LEGACY_APP_URL: http://router
      LEGACY_APP_COOKIE_DOMAIN: ${BEABEE_COOKIE_DOMAIN}
      FRONTEND_APP_URL: http://frontend
    ports:
      - ${MAIN_PORT}:80
