version: '3.4'

x-app: &app
  restart: always
  env_file:
    - .env
  logging:
    driver: syslog
    options:
      tag: docker/{{.Name}}

services:
  app:
    <<: *app
    image: beabee/beabee-legacy-app:release

  api_app:
    <<: *app
    image: beabee/beabee-api-app:release

  webhook_app:
    <<: *app
    image: beabee/beabee-webhook-app:release

  cron_app:
    <<: *app
    image: beabee/beabee-cron-app:release

  img_upload_app:
    image: beabee/pictshare:release
    restart: always
    environment:
      URL: ${BEABEE_AUDIENCE}/uploads/
    volumes:
      - ./data/uploads:/var/www/data

  run:
    <<: *app
    image: beabee/beabee-api-app:release
    profiles:
      - tools
    logging:
      driver: none

  frontend:
    image: beabee/frontend:release
    restart: always
    environment:
      APP_BASE_URL: ${BEABEE_AUDIENCE}
      API_BASE_URL: /api/1.0
      APPSIGNAL_KEY: ${APPSIGNAL_KEY-}
      MAPTILER_KEY: ${BEABEE_MAPTILER_KEY-}
      EXPERIMENTAL_FEATURES: ${BEABEE_EXPERIMENTAL_FEATURES-}

  app_router:
    image: beabee/beabee-router:latest
    restart: always
    environment:
      LEGACY_APP_COOKIE_DOMAIN: ${BEABEE_COOKIE_DOMAIN}
      TRUSTED_ORIGINS: ${BEABEE_TRUSTEDORIGINS-}
    ports:
      - ${MAIN_PORT}:80
