x-app: &app
  restart: always
  env_file:
    - .env
  logging:
    driver: syslog
    options:
      tag: docker/{{.Name}}

services:
  app:
    <<: *app
    image: beabee/beabee-legacy-app:release

  api_app:
    <<: *app
    image: beabee/beabee-api-app:release

  webhook_app:
    <<: *app
    image: beabee/beabee-webhook-app:release

  cron_app:
    <<: *app
    image: beabee/beabee-cron-app:release

  minio:
    image: beabee/beabee-minio:release
    restart: always
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${BEABEE_MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${BEABEE_MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_REGION: ${BEABEE_MINIO_REGION:-us-east-1}
      BEABEE_MINIO_BUCKET: ${BEABEE_MINIO_BUCKET:-uploads}
      BEABEE_MINIO_ENDPOINT: ${BEABEE_MINIO_ENDPOINT:-http://minio:9000}

  run:
    <<: *app
    image: beabee/beabee-api-app:release
    profiles:
      - tools
    logging:
      driver: none

  frontend:
    image: beabee/beabee-frontend:release
    restart: always
    environment:
      APP_BASE_URL: ${BEABEE_AUDIENCE}
      API_BASE_URL: /api/1.0
      EXPERIMENTAL_FEATURES: ${BEABEE_EXPERIMENTAL_FEATURES-}
      APPSIGNAL_KEY: ${APPSIGNAL_KEY-}
      CAPTCHAFOX_KEY: ${BEABEE_CAPTCHAFOX_KEY-}
      MAPTILER_KEY: ${BEABEE_MAPTILER_KEY-}

  app_router:
    image: beabee/beabee-router:release
    restart: always
    environment:
      LEGACY_APP_COOKIE_DOMAIN: ${BEABEE_COOKIE_DOMAIN}
      TRUSTED_ORIGINS: ${BEABEE_TRUSTEDORIGINS-}
    ports:
      - ${MAIN_PORT}:80
    depends_on:
      - api_app
      - app
      - frontend
      - webhook_app

volumes:
  minio_data: