version: '3.4'

x-app: &app
  image: thebristolcable/beabee:latest
  volumes:
    - ./config:/opt/membership-system/built/config
  env_file:
    - .env
  logging:
    driver: syslog
    options:
      tag: docker/{{.Name}}

services:
  app: *app

  gc_webhook:
    <<: *app
    command: 'node built/webhooks/gocardless'

  stripe_webhook:
    <<: *app
    command: 'node built/webhooks/stripe'

  cron:
    <<: *app
    user: root
    command: 'crond -f -d 0'

  router:
    image: thebristolcable/router:latest
    volumes:
      - ./data/uploads:/opt/membership-system/built/uploads:ro
    ports:
      - ${PORT}:80

  run:
    <<: *app
    profiles:
      - tools
    logging:
      driver: none
