version: '3.4'

x-app: &app
  image: beabee/beabee:latest
  volumes:
    - ./config:/opt/membership-system/built/config
  env_file:
    - .env
  logging:
    driver: syslog
    options:
      tag: docker/{{.Name}}

services:
  app: *app

  api_app:
    <<: *app
    command: 'node built/api/app'

  webhook_app:
    <<: *app
    command: 'node built/webhooks/app'

  cron:
    <<: *app
    user: root
    command: 'crond -f -d 0'
    init: true

  router:
    image: beabee/router:latest
    volumes:
      - ./data/uploads:/opt/membership-system/built/uploads:ro
      - ./data/favicon:/opt/membership-system/built/static/favicon:ro

  run:
    <<: *app
    profiles:
      - tools
    logging:
      driver: none

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        THEME: ${THEME}
        AUDIENCE_URL: ${AUDIENCE_URL}
        SERVER_API_URL: ${SERVER_API_URL}
    init: true

  frontend_router:
    image: beabee/frontend-router:latest
    env_file:
      - .env
    environment:
      OLD_FRONTEND_URL: http://router
    ports:
      - ${MAIN_PORT}:80
